version: "3.8"

services:

  gatling:
    image: gatling:latest
    deploy:
      mode: replicated
      replicas: 3
      rollback_config:
        parallelism: 0
      restart_policy:
        condition: none
